// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PharmaBlockchainBackend.Infrastructure;

#nullable disable

namespace PharmaBlockchainBackend.Infrastructure.Migrations
{
    [DbContext(typeof(PharmaBlockchainBackendDbContext))]
    [Migration("20251225123231_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PharmaBlockchainBackend.Infrastructure.Entities.Cmo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("Id");

                    b.ToTable("Cmo");
                });

            modelBuilder.Entity("PharmaBlockchainBackend.Infrastructure.Entities.Package", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Code")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PalletId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PalletId");

                    b.ToTable("Package");
                });

            modelBuilder.Entity("PharmaBlockchainBackend.Infrastructure.Entities.Pallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Code")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Pallet");
                });

            modelBuilder.Entity("PharmaBlockchainBackend.Infrastructure.Entities.ProtocolStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdditionalData")
                        .HasColumnType("text");

                    b.Property<Guid>("CmoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PalletId")
                        .HasColumnType("uuid");

                    b.Property<int>("ProtocolType")
                        .HasColumnType("integer");

                    b.Property<int>("StepNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CmoId");

                    b.HasIndex("PackageId");

                    b.HasIndex("PalletId");

                    b.ToTable("ProtocolStep");
                });

            modelBuilder.Entity("PharmaBlockchainBackend.Infrastructure.Entities.Package", b =>
                {
                    b.HasOne("PharmaBlockchainBackend.Infrastructure.Entities.Pallet", "Pallet")
                        .WithMany("Packages")
                        .HasForeignKey("PalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pallet");
                });

            modelBuilder.Entity("PharmaBlockchainBackend.Infrastructure.Entities.ProtocolStep", b =>
                {
                    b.HasOne("PharmaBlockchainBackend.Infrastructure.Entities.Cmo", "Cmo")
                        .WithMany("ProtocolSteps")
                        .HasForeignKey("CmoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmaBlockchainBackend.Infrastructure.Entities.Package", "Package")
                        .WithMany("ProtocolSteps")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmaBlockchainBackend.Infrastructure.Entities.Pallet", "Pallet")
                        .WithMany("ProtocolSteps")
                        .HasForeignKey("PalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cmo");

                    b.Navigation("Package");

                    b.Navigation("Pallet");
                });

            modelBuilder.Entity("PharmaBlockchainBackend.Infrastructure.Entities.Cmo", b =>
                {
                    b.Navigation("ProtocolSteps");
                });

            modelBuilder.Entity("PharmaBlockchainBackend.Infrastructure.Entities.Package", b =>
                {
                    b.Navigation("ProtocolSteps");
                });

            modelBuilder.Entity("PharmaBlockchainBackend.Infrastructure.Entities.Pallet", b =>
                {
                    b.Navigation("Packages");

                    b.Navigation("ProtocolSteps");
                });
#pragma warning restore 612, 618
        }
    }
}
